spring:
  application:
    name: user-service

  datasource:
    url: jdbc:mysql://localhost:3306/user_db
    username: root
    password: ironfish54
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
